# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_favorite_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
    ]
